In [3]:
# imports
import pandas as pd
from datasets import load_dataset
from evaluator import Evaluator

In [4]:
# load the Splits! dataset
splits = load_dataset("ecaplan/splits", "splits")
# all versions of the dataset contain only a 'train' portion
splits = splits['train']

In [5]:
# convert the huggingface dataset to a pandas dataframe
df = pd.DataFrame(splits)

In [10]:
# since the full dataset has >176k samples, we will use a smaller sample for testing
sample_size = 10
# batch size for ~4k tokens on Llama-3.1-70B (raise at your own risk)
batch_size = 1

In [11]:
# sample the dataframe
sample_df = df.sample(sample_size, random_state=42)
sample_df

,description,sample_A,sample_B,demographic_A,demographic_B,switched,example_posts
140446,Side Hustles/Additional Income,[Oh we totally won with a variable rate on our...,"[Oh, it's definitely earned income. They're 10...",black,construction,True,[Keep in mind that $700 is on the high side of...
100685,Medical & Healthcare Professions,[If people have access to the healthcare they ...,[That makes sence..\n However there is a short...,construction,teacher,True,[There were plenty of targets out in the open ...
34143,"Consoles (PlayStation, Xbox, Nintendo)",[Did you play Halo Wars on xbox? Apparently it...,"[I definitely do more local than online, but t...",catholic,teacher,False,[Thanks for the response. I had a test run of ...
16435,Birdwatching,[Sea World in Texas built a large basin and fi...,[Originally I lived in rural Finland... closes...,catholic,teacher,True,[No way it's like tiny wings. It's more like t...
155705,Swimming,[no idea how an olympic-size swimming pool cou...,[I'm always surprised by how many people don't...,catholic,construction,True,[SWIM always wondered about that. They had a p...
67814,Freelancing,[If you cannot work you'll need to go to your ...,"[As a freelance writer, baby sitter and tutor....",catholic,teacher,False,[As someone who reads too many webcomics and h...
84152,Index Funds & ETFs,[Hope all those RH traders had fun at the open...,[This market is so stupid smh. WE ALL KNEW THE...,black,construction,True,"[That's not totally true. Top schools, both pu..."
176622,Yoga,"[I didn't say they should stop protesting, I s...",[:)\n\nPerhaps you could find a day-long works...,jewish,teacher,False,[I don't want to ruin your parade but those of...
142083,Skateboarding,"[No, not very different at all. The issues aro...",[Spike wasn't utilizing them to that effect. M...,black,catholic,True,[[Skate Aranha - Evil & Dead](https://www.yout...
141901,Sitcoms,"[Lol... this is comedy my friend., The Grand (...",[This made me puke then and it makes me puke n...,construction,teacher,False,"[Same here, except I wasn't laughing I was jus..."

In [14]:
# now let's make some theories!
# in this example, we will make a really simple theory that says that group A uses more commas than group B when talking about the topic
# in general, your method can use the two groups, the topic, and the calibration set to make a theory
theories = []

for i, row in sample_df.iterrows():
    demo_A = row['demographic_A']
    demo_B = row['demographic_B']
    topic = row['description']
    calibration_set = row['example_posts']

    # make a theory for each row
    theory = f"People who are '{row['demographic_A']}' use more commas than people who are '{row['demographic_B']}' when talking about '{row['description']}'."
    theories.append(theory)



sample_df['theory'] = theories
sample_df

,description,sample_A,sample_B,demographic_A,demographic_B,switched,example_posts,theory
140446,Side Hustles/Additional Income,[Oh we totally won with a variable rate on our...,"[Oh, it's definitely earned income. They're 10...",black,construction,True,[Keep in mind that $700 is on the high side of...,People who are 'black' use more commas than pe...
100685,Medical & Healthcare Professions,[If people have access to the healthcare they ...,[That makes sence..\n However there is a short...,construction,teacher,True,[There were plenty of targets out in the open ...,People who are 'construction' use more commas ...
34143,"Consoles (PlayStation, Xbox, Nintendo)",[Did you play Halo Wars on xbox? Apparently it...,"[I definitely do more local than online, but t...",catholic,teacher,False,[Thanks for the response. I had a test run of ...,People who are 'catholic' use more commas than...
16435,Birdwatching,[Sea World in Texas built a large basin and fi...,[Originally I lived in rural Finland... closes...,catholic,teacher,True,[No way it's like tiny wings. It's more like t...,People who are 'catholic' use more commas than...
155705,Swimming,[no idea how an olympic-size swimming pool cou...,[I'm always surprised by how many people don't...,catholic,construction,True,[SWIM always wondered about that. They had a p...,People who are 'catholic' use more commas than...
67814,Freelancing,[If you cannot work you'll need to go to your ...,"[As a freelance writer, baby sitter and tutor....",catholic,teacher,False,[As someone who reads too many webcomics and h...,People who are 'catholic' use more commas than...
84152,Index Funds & ETFs,[Hope all those RH traders had fun at the open...,[This market is so stupid smh. WE ALL KNEW THE...,black,construction,True,"[That's not totally true. Top schools, both pu...",People who are 'black' use more commas than pe...
176622,Yoga,"[I didn't say they should stop protesting, I s...",[:)\n\nPerhaps you could find a day-long works...,jewish,teacher,False,[I don't want to ruin your parade but those of...,People who are 'jewish' use more commas than p...
142083,Skateboarding,"[No, not very different at all. The issues aro...",[Spike wasn't utilizing them to that effect. M...,black,catholic,True,[[Skate Aranha - Evil & Dead](https://www.yout...,People who are 'black' use more commas than pe...
141901,Sitcoms,"[Lol... this is comedy my friend., The Grand (...",[This made me puke then and it makes me puke n...,construction,teacher,False,"[Same here, except I wasn't laughing I was jus...",People who are 'construction' use more commas ...

In [ ]:
# now let's load the classification model (make sure you have access to meta-llama/Llama-3.1-70B-Instruct through huggingface)
evaluator = Evaluator(sample_df, batch_size=batch_size)

Downloading shards:  63%|██████▎   | 19/30 [00:06<00:03,  2.97it/s]

KeyboardInterrupt:

In [ ]:
# and let's evaluate the theories! (this can take a while)
evaluator.evaluate()